---
version: "3.7"
services:
  
  dev:
    container_name: nestjs_api_dev
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  mysql: 
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    volumes:
        - mysqldb:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: library
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma 
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

volumes:
  mysqldb: 
  node_modules:
